# Generated by Django 5.0.1 on 2024-02-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('receiptImage', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
    ]
